title: Sinji Blog
description: > # this means to ignore newlines until "baseurl:"
  저를 소개하는 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinji2102.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Yun Sinji
tagline: FrontEnd Developer
about-description: 저는 국민대학교에 재학 중인 22살 윤신지입니다. 용문고 학생들 파이팅 하세요!
pic: 쿠민.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: sinji.3010@gmail.com # Add your Email address
phone: 010-2247-9474 # Add your Phone number
website: https://velog.io/@dawnww/posts # Add your website, do not add http://
github: sinji2102 # Add your Github handle
instagram: 'd_awnww' # Add your Twitter handle

















# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
