# Site settings
title: github.io
# baseurl: "/ap"
url: "https://kssim.github.io"
google_analytics: G-SP2R0K5HJ4

# Author
author:
  name: Sinji Yun
  desc: 국민대학교 20223109
  email: sinji.3010@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: sinji2102
  google_plus:
  instagram: d_awnww
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

# Custom vars
comment:
  provider: "disqus"
  dispus:
    shortname: "sinji2102"
