title: sinji blog
description: > # this means to ignore newlines until "baseurl:"
  저를 소개하는 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinji2102.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Sinji Yun
tagline: FrontEnd Developer
about-description: 문제를 해결할 때 기쁨을 느끼는 웹 개발자 윤신지입니다. 어쩌고 저쩌고 자기소개 작성해 주시면 됩니다! 용문고 학생들 파이팅하세요 🔥
pic: 79.jpg  

# Contact links
email: sinji.3010@gmail.com # Add your Email address
phone: 010-2247-9474 # Add your Phone number
website: velog.io/@dawnww/posts # Add your website, do not add http://
github: sinji2102 # Add your Github handle
instagram: 'd_awnww'

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
